import Foundation

/// Exports the visual project into clean, idiomatic, fully functional SwiftUI code.
struct SwiftCodeGenerator {
    static func generate(project: BuilderProject) -> String {
        let appTypeName = swiftIdentifier(project.document.appName)
        let primaryScreenName = project.document.screens.first?.name ?? "Home"
        let power = project.customSwift.trimmingCharacters(in: .whitespacesAndNewlines)
        let powerSection = power.isEmpty
            ? "// Add advanced custom Swift in App Builder's Swift tab."
            : "// MARK: - Custom Swift Power Code\n\(power)"

        var stateVariablesDeclarations = ""
        for v in project.document.globalVariables {
            switch v.type {
            case .number:
                stateVariablesDeclarations += "    @State private var \(v.name): Double = \(v.numberValue)\n"
            case .text:
                stateVariablesDeclarations += "    @State private var \(v.name): String = \"\(v.textValue)\"\n"
            case .boolean:
                stateVariablesDeclarations += "    @State private var \(v.name): Bool = \(v.boolValue)\n"
            case .list:
                let listItems = v.listValue.map { "\"" + $0 + "\"" }.joined(separator: ", ")
                stateVariablesDeclarations += "    @State private var \(v.name): [String] = [\(listItems)]\n"
            }
        }

        var screensCode = ""
        for screen in project.document.screens {
            screensCode += generateScreenView(screen, project: project)
            screensCode += "\n\n"
        }

        let screensCases = project.document.screens.map {
            let bindings = passBindings(for: project)
            return "                case \"\($0.name)\": \(swiftIdentifier($0.name))View(currentScreen: $currentScreen\(bindings))"
        }.joined(separator: "\n")

        return """
// Generated by App Builder
// Real standalone SwiftUI application ready to run in Xcode or Swift Playgrounds.

import SwiftUI
import AVFoundation
import UIKit

@main
struct \(appTypeName)App: App {
    var body: some Scene {
        WindowGroup {
            MainContentView()
        }
    }
}

// MARK: - Main Root View & Navigation

struct MainContentView: View {
    @State private var currentScreen: String = "\(primaryScreenName)"
\(stateVariablesDeclarations)
    var body: some View {
        NavigationStack {
            ZStack {
                switch currentScreen {
\(screensCases)
                default:
                    Text("Screen not found")
                }
            }
        }
    }
}

// MARK: - App Screen Views

\(screensCode)

// MARK: - Built-in Waveform Sound Synthesizer

@MainActor
final class ExportedSoundSynthesizer {
    static let shared = ExportedSoundSynthesizer()
    private var players: [String: AVAudioPlayer] = [:]

    func play(_ name: String) {
        guard let data = generateTone(for: name), let player = try? AVAudioPlayer(data: data) {
            player.play()
            players[name] = player
        }
    }

    private func generateTone(for name: String) -> Data? {
        let sampleRate: Double = 22050
        var samples: [Float] = []
        let len = Int(sampleRate * 0.15)
        for i in 0..<len {
            let t = Double(i) / sampleRate
            let freq = name.contains("laser") ? (800.0 - t * 4000.0) : 880.0
            let env = 1.0 - (Double(i) / Double(len))
            samples.append(Float(sin(2.0 * .pi * max(100.0, freq) * t) * env * 0.4))
        }

        var data = Data()
        data.append(contentsOf: "RIFF".utf8)
        let chunkSize = UInt32(36 + samples.count * 2)
        data.append(withUnsafeBytes(of: chunkSize.littleEndian) { Data($0) })
        data.append(contentsOf: "WAVEfmt ".utf8)
        data.append(withUnsafeBytes(of: UInt32(16).littleEndian) { Data($0) })
        data.append(withUnsafeBytes(of: UInt16(1).littleEndian) { Data($0) })
        data.append(withUnsafeBytes(of: UInt16(1).littleEndian) { Data($0) })
        data.append(withUnsafeBytes(of: UInt32(sampleRate).littleEndian) { Data($0) })
        data.append(withUnsafeBytes(of: UInt32(sampleRate * 2).littleEndian) { Data($0) })
        data.append(withUnsafeBytes(of: UInt16(2).littleEndian) { Data($0) })
        data.append(withUnsafeBytes(of: UInt16(16).littleEndian) { Data($0) })
        data.append(contentsOf: "data".utf8)
        data.append(withUnsafeBytes(of: UInt32(samples.count * 2).littleEndian) { Data($0) })
        for s in samples {
            let intS = Int16(s * 32767.0)
            data.append(withUnsafeBytes(of: intS.littleEndian) { Data($0) })
        }
        return data
    }
}

\(powerSection)
"""
    }

    private static func generateScreenView(_ screen: AppScreen, project: BuilderProject) -> String {
        let viewName = "\(swiftIdentifier(screen.name))View"
        var bindingsDecl = "    @Binding var currentScreen: String\n"
        for v in project.document.globalVariables {
            switch v.type {
            case .number: bindingsDecl += "    @Binding var \(v.name): Double\n"
            case .text: bindingsDecl += "    @Binding var \(v.name): String\n"
            case .boolean: bindingsDecl += "    @Binding var \(v.name): Bool\n"
            case .list: bindingsDecl += "    @Binding var \(v.name): [String]\n"
            }
        }

        var elementsCode = ""
        for el in screen.elements {
            elementsCode += generateElementCode(el)
            elementsCode += "\n"
        }

        return """
struct \(viewName): View {
\(bindingsDecl)
    var body: some View {
        ZStack(alignment: .topLeading) {
            Color(hex: "\(screen.backgroundColorHex)")
                .ignoresSafeArea()

\(elementsCode)
        }
    }
}
"""
    }

    private static func generateElementCode(_ el: AppElement) -> String {
        let color = "Color(hex: \"\(el.colorHex)\")"
        let textColor = "Color(hex: \"\(el.textColorHex)\")"
        let frame = ".frame(width: \(Int(el.width)), height: \(Int(el.height)))"
        let offset = ".offset(x: \(Int(el.x)), y: \(Int(el.y)))"

        var content = ""
        switch el.kind {
        case .button:
            var actions = ""
            for a in el.onTapActions {
                if a.kind == .setVariable {
                    actions += "                    \(a.targetVariable) += \(a.expression)\n"
                } else if a.kind == .navigate {
                    actions += "                    currentScreen = \"\(a.targetScreenName)\"\n"
                } else if a.kind == .playSound {
                    actions += "                    ExportedSoundSynthesizer.shared.play(\"\(a.sound.rawValue)\")\n"
                }
            }
            content = """
            Button {
                withAnimation(.spring()) {
\(actions)                }
            } label: {
                Text("\(escape(el.text))")
                    .font(.system(size: \(Int(el.fontSize)), weight: .\(el.fontWeight.rawValue.lowercased())))
                    .foregroundStyle(\(textColor))
                    \(frame)
                    .background(\(color), in: RoundedRectangle(cornerRadius: \(Int(el.cornerRadius))))
            }
"""
        case .icon:
            content = """
            Image(systemName: "\(el.iconName)")
                .resizable()
                .scaledToFit()
                .foregroundStyle(\(color))
                \(frame)
"""
        case .text:
            let txt = !el.boundVariable.isEmpty ? "\\(\(el.boundVariable))" : escape(el.text)
            content = """
            Text("\(txt)")
                .font(.system(size: \(Int(el.fontSize)), weight: .\(el.fontWeight.rawValue.lowercased())))
                .foregroundStyle(\(textColor))
                \(frame)
"""
        case .shape:
            content = """
            RoundedRectangle(cornerRadius: \(Int(el.cornerRadius)))
                .fill(\(color))
                \(frame)
"""
        case .progressBar:
            let bound = !el.boundVariable.isEmpty ? el.boundVariable : "50"
            content = """
            ProgressView(value: min(1.0, max(0.0, \(bound) / \(el.maxValue))))
                .tint(\(color))
                \(frame)
"""
        default:
            content = """
            RoundedRectangle(cornerRadius: \(Int(el.cornerRadius)))
                .fill(\(color))
                \(frame)
"""
        }

        return "\(content)\n            \(offset)"
    }

    private static func passBindings(for project: BuilderProject) -> String {
        var str = ""
        for v in project.document.globalVariables {
            str += ", \(v.name): $\(v.name)"
        }
        return str
    }

    static func playgroundPackage(project: BuilderProject) -> [String: Data] {
        let source = generate(project: project)
        let package = """
// swift-tools-version: 5.9
import PackageDescription
import AppleProductTypes

let package = Package(
    name: "\(swiftIdentifier(project.name))",
    platforms: [.iOS(.v16)],
    products: [
        .iOSApplication(
            name: "\(swiftIdentifier(project.name))",
            targets: ["App"],
            bundleIdentifier: "com.arena.\(swiftIdentifier(project.name).lowercased())",
            teamIdentifier: "",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .magicWand),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [.pad, .phone],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(name: "App", path: "Sources/App")
    ]
)
"""
        let readme = """
# \(project.name)

Exported from App Builder.
Fully interactive SwiftUI app with audio synthesis, 60fps animations, reactive state variables, and multi-screens.
"""
        return [
            "Package.swift": Data(package.utf8),
            "Sources/App/App.swift": Data(source.utf8),
            "README.md": Data(readme.utf8)
        ]
    }

    private static func swiftIdentifier(_ name: String) -> String {
        let valid = name.components(separatedBy: CharacterSet.alphanumerics.inverted).joined()
        let clean = valid.trimmingCharacters(in: .whitespacesAndNewlines)
        return clean.isEmpty ? "App" : clean
    }

    private static func escape(_ str: String) -> String {
        str.replacingOccurrences(of: "\\", with: "\\\\").replacingOccurrences(of: "\"", with: "\\\"")
    }
}
