import Foundation

struct SwiftCodeGenerator {
    static func generate(project: BuilderProject) -> String {
        // A playground imported from elsewhere may already contain its own @main.
        // Preserve that complete source instead of creating two application entry points.
        let imported = project.customSwift.trimmingCharacters(in: .whitespacesAndNewlines)
        if imported.contains("@main") && imported.contains("import SwiftUI") {
            return "// Preserved imported source from App Builder.\n\(imported)\n"
        }

        let typeName = swiftIdentifier(project.document.appName)
        let appName = escape(project.document.appName)
        let root = render(project.document.root, indent: 3)
        let power = project.customSwift.trimmingCharacters(in: .whitespacesAndNewlines)
        let powerSection = power.isEmpty
            ? "// Add advanced Swift in App Builder's Power code tab."
            : "// MARK: - Power code (kept from the visual editor)\n\(power)"

        return """
// This file was generated by App Builder.
// Visual blocks are intentionally ordinary SwiftUI, so this is a real Swift app.
// You can keep editing the Power code section or open the project in Swift Playgrounds.

import SwiftUI

@main
struct \(typeName)App: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

struct ContentView: View {
    @State private var appToggle = false
    @State private var appSlider = 0.5
    @State private var appText = ""

    var body: some View {
        NavigationStack {
\(root)
        }
    }
}

// MARK: - Project information
// App name: \(appName)

\(powerSection)
"""
    }

    static func playgroundPackage(project: BuilderProject) -> [String: Data] {
        let source = generate(project: project)
        let package = """
// swift-tools-version: 5.9
import PackageDescription
import AppleProductTypes

let package = Package(
    name: "\(swiftIdentifier(project.name))",
    platforms: [.iOS(.v16)],
    products: [
        .iOSApplication(
            name: "\(swiftIdentifier(project.name))",
            targets: ["App"],
            bundleIdentifier: "com.example.\(swiftIdentifier(project.name).lowercased())",
            teamIdentifier: "",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .magicWand),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [.pad, .phone],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(name: "App", path: "Sources/App")
    ]
)
"""
        let readme = """
# \(project.name)

Generated by App Builder. Open this `.swiftpm` package in Swift Playgrounds on iPadOS.
The source in `Sources/App/App.swift` is ordinary SwiftUI and can be extended freely.
"""
        return [
            "Package.swift": Data(package.utf8),
            "Sources/App/App.swift": Data(source.utf8),
            "README.md": Data(readme.utf8)
        ]
    }

    private static func render(_ block: BuilderBlock, indent: Int) -> String {
        let spaces = String(repeating: "    ", count: indent)
        let childIndent = indent + 1
        let children = block.children.map { render($0, indent: childIndent) }.joined(separator: "\n")
        let safeChildren = children.isEmpty ? String(repeating: "    ", count: childIndent) + "EmptyView()" : children
        let title = escape(block.title)
        let value = escape(block.value)
        let color = swiftColor(block.colorHex)

        switch block.kind {
        case .verticalStack:
            return "\(spaces)VStack(alignment: .leading, spacing: 14) {\n\(safeChildren)\n\(spaces)}"
        case .horizontalStack:
            return "\(spaces)HStack(spacing: 12) {\n\(safeChildren)\n\(spaces)}"
        case .zStack:
            return "\(spaces)ZStack {\n\(safeChildren)\n\(spaces)}"
        case .spacer:
            return "\(spaces)Spacer(minLength: 12)"
        case .padding:
            return "\(spaces)VStack {\n\(safeChildren)\n\(spaces)}.padding(16)"
        case .text:
            return "\(spaces)Text(\"\(title)\").font(.title3).foregroundStyle(\(color))"
        case .image:
            let icon = block.title.isEmpty ? "star.fill" : title
            return "\(spaces)Image(systemName: \"\(icon)\").font(.system(size: 42, weight: .semibold)).foregroundStyle(\(color))"
        case .colorBox:
            return "\(spaces)RoundedRectangle(cornerRadius: 18).fill(\(color)).frame(minHeight: 76)"
        case .divider:
            return "\(spaces)Divider()"
        case .badge:
            return "\(spaces)Text(\"\(title)\").font(.caption.weight(.semibold)).padding(.horizontal, 10).padding(.vertical, 6).background(\(color), in: Capsule())"
        case .button:
            let actionComment = block.secondaryValue.isEmpty ? "// Add an action in Power code" : "// \(escape(block.secondaryValue))"
            return "\(spaces)Button(\"\(title)\") {\n\(spaces)    \(actionComment)\n\(spaces)}.buttonStyle(.borderedProminent)"
        case .navigationLink:
            return "\(spaces)NavigationLink(\"\(title)\", destination: Text(\"Next screen\").font(.title))"
        case .toggle:
            return "\(spaces)Toggle(\"\(title)\", isOn: $appToggle)"
        case .slider:
            return "\(spaces)VStack(alignment: .leading) { Text(\"\(title)\"); Slider(value: $appSlider, in: 0...1) }"
        case .textField:
            return "\(spaces)TextField(\"\(title)\", text: $appText)\n\(spaces)    .textFieldStyle(.roundedBorder)"
        case .list:
            let row = title.isEmpty ? "Item" : title
            return "\(spaces)ForEach(0..<3, id: \\.self) { index in\n\(spaces)    Text(\"\(row) \\(index + 1)\")\n\(spaces)}"
        case .state:
            let stateName = swiftIdentifier(block.title.isEmpty ? "value" : block.title)
            let initial = value.isEmpty ? "0" : value
            return "\(spaces)Text(\"State: \(stateName) = \(initial)\")"
        case .conditional:
            let condition = block.title.isEmpty ? "true" : block.title
            return "\(spaces)Group {\n\(spaces)    if \(condition) {\n\(safeChildren)\n\(spaces)    }\n\(spaces)}"
        case .repeatBlock:
            let count = Int(block.title) ?? 3
            return "\(spaces)ForEach(0..<\(max(0, count)), id: \\.self) { _ in\n\(safeChildren)\n\(spaces)}"
        case .event:
            return "\(spaces)VStack(alignment: .leading, spacing: 8) {\n\(spaces)    Text(\"\(title)\").font(.caption).foregroundStyle(.secondary)\n\(safeChildren)\n\(spaces)}"
        case .rawSwift:
            let expression = block.title.isEmpty ? "Text(\"Custom Swift view\")" : block.title
            return "\(spaces)AnyView(\(expression))"
        }
    }

    private static func escape(_ text: String) -> String {
        text.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
    }

    private static func swiftIdentifier(_ text: String) -> String {
        let pieces = text.split(whereSeparator: { !$0.isLetter && !$0.isNumber })
        var result = pieces.map { piece in
            let string = String(piece)
            return String(string.prefix(1)).uppercased() + String(string.dropFirst())
        }.joined()
        if result.isEmpty { result = "AppBuilderProject" }
        if result.first?.isNumber == true { result = "App" + result }
        return result
    }

    private static func swiftColor(_ hex: String) -> String {
        let clean = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        let value = UInt64(clean, radix: 16) ?? 0x6C5CE7
        let red = Double((value >> 16) & 0xFF) / 255
        let green = Double((value >> 8) & 0xFF) / 255
        let blue = Double(value & 0xFF) / 255
        return String(format: "Color(red: %.3f, green: %.3f, blue: %.3f)", red, green, blue)
    }
}
